export const ADS = [
  {
    id: 'topup_bonus',
    placements: ['global_bottom', 'home_top', 'wallet_inline'],
    weight: 5,
    sponsor: 'Promoted',
    title: 'Bonus Top-Up',
    headline: 'Get bonus on top-up',
    body: 'Limited time. Add funds and unlock extra rounds.',
    primaryCta: 'Top up',
    secondaryCta: 'Details',
    primaryUrl: '/wallet',
    secondaryUrl: '/how-to-play',
    cooldownMs: 1000 * 60 * 5,
    maxImpressionsPerDay: 20,
  },
  {
    id: 'vip_rounds',
    placements: ['home_top', 'ads_feed'],
    weight: 3,
    sponsor: 'Sponsored',
    title: 'VIP Rounds',
    headline: 'Faster rounds, bigger thrill',
    body: 'Upgrade to premium speed modes and get access to exclusive streak boosts.',
    primaryCta: 'See VIP',
    secondaryCta: 'Later',
    primaryUrl: '/ads',
    secondaryUrl: '/how-to-play',
    cooldownMs: 1000 * 60 * 10,
    maxImpressionsPerDay: 15,
  },
  {
    id: 'refer_earn',
    placements: ['global_bottom', 'ads_feed'],
    weight: 4,
    sponsor: 'Partner',
    title: 'Refer & Earn',
    headline: 'Invite friends, earn rewards',
    body: 'Share your invite and get rewards when friends play their first rounds.',
    primaryCta: 'Invite',
    secondaryCta: 'Rules',
    primaryUrl: '/ads',
    secondaryUrl: '/how-to-play',
    cooldownMs: 1000 * 60 * 15,
    maxImpressionsPerDay: 12,
  },
  {
    id: 'help_tips',
    placements: ['howto_inline'],
    weight: 2,
    sponsor: 'Sponsored',
    title: 'Pro Tips',
    headline: 'Learn the patterns',
    body: 'Check strategies, avoid chasing losses, and manage your bankroll for longer sessions.',
    primaryCta: 'Read tips',
    secondaryCta: 'Skip',
    primaryUrl: '/how-to-play',
    secondaryUrl: '/',
    cooldownMs: 1000 * 60 * 30,
    maxImpressionsPerDay: 8,
  },
]

export const DEFAULT_AD_ROTATION_OPTIONS = {
  historySize: 4,
}
